### ISSUE TITLE
libicui18n fails to compile on Windows with MSVC 19.36.32502 due to P2468R2

### ISSUE THREAD

**Issue by wroyca** [build2-packaging/icu#1]
The meaning of == and != expressions has been altered in C++20 with the proposals P1185R2 and P2468R2, along with changes to how overload resolution is applied to them, resulting in previously valid code becoming invalid. As a result, ICU now produces error C2666 on certain overloaded functions and operators. Due to certain packages such as Qt being dependent on ICU, it also becomes infeasible to compile them.

&nbsp;&nbsp;&nbsp;&nbsp;https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2468r2.html

```powershell
b
c++ ..\echo-msvc\libicui18n-65.1.0+6\libicui18n\i18n\cxx{fmtable} -> ..\echo-msvc\libicui18n-65.1.0+6\libicui18n\i18n\objs{fmtable}
c++ ..\echo-msvc\libicui18n-65.1.0+6\libicui18n\i18n\cxx{fmtable} -> ..\echo-msvc\libicui18n-65.1.0+6\libicui18n\i18n\obja{fmtable}
C:\Users\wroy\Desktop\echo-msvc\libicui18n-65.1.0+6\libicui18n\i18n\fmtable.cpp(59): error C2666: 'icu_65::Measure::operator ==': overloaded functions have similar conversions
C:\Users\wroy\Desktop\echo-msvc\libicui18n-65.1.0+6\libicui18n\i18n\unicode/measure.h(90): note: could be 'UBool icu_65::Measure::operator ==(const icu_65::UObject &) const'
C:\Users\wroy\Desktop\echo-msvc\libicuuc-65.1.0+6\libicu/uc\unicode/stringpiece.h(242): note: or       'UBool icu_65::operator ==(const icu_65::StringPiece &,const icu_65::StringPiece &)'
C:\Users\wroy\Desktop\echo-msvc\libicui18n-65.1.0+6\libicui18n\i18n\unicode/measure.h(90): note: or 'UBool icu_65::Measure::operator ==(const icu_65::UObject &) const' [synthesized expression 'y == x']
C:\Users\wroy\Desktop\echo-msvc\libicuuc-65.1.0+6\libicu/uc\unicode/stringpiece.h(242): note: or 'UBool icu_65::operator ==(const icu_65::StringPiece &,const icu_65::StringPiece &)' [synthesized expression 'y == x']
C:\Users\wroy\Desktop\echo-msvc\libicui18n-65.1.0+6\libicui18n\i18n\fmtable.cpp(59): note: while trying to match the argument list '(const icu_65::Measure, const icu_65::Measure)'
error: process cl exited with code 2
```

**Comment by boris-kolpackov** [comment]
Thanks for the report. Do you know by any chance if this has been fixed in newer versions of ICU? We are overdue for an upgrade.

**Comment by boris-kolpackov** [comment]
This looks better. Can you confirm that this fixes all the compilation errors in this MSVC version?

**Comment by boris-kolpackov** [comment]
@wroyca Do you know if there is an upstream's official fix/patch for this yet?

**Comment by boris-kolpackov** [comment]
Also, 19.36.32502 is (currently) the preview version of MSVC 17.6, correct?

**Comment by boris-kolpackov** [comment]
I just checked 72.1 and while they didn't add the `!=` overload, they did change the return type to `bool`. I've also checked the current development version (the `main` branch) and there is nothing new there in this regard. So perhaps that's enough? It would have been helpful if you could test this change (i.e., change `UBool` to `bool` instead of adding the `!=` overload) and confirm it helps (we don't deploy preview versions of MSVC to our CI so we cannot test this ourselves).

**Comment by boris-kolpackov** [comment]
> Confirmed that the issue is still present [...]
>
> ```
> measure.h(90): note: could be 'UBool icu_65::Measure::operator ==(const icu_65::UObject &) const'
> ```

Not sure what this is confirming since it still seems to use `UBool`. Can you: (1) revert your patch (or rebuild from scratch), (2) replace `Ubool` with `bool` (both in declaration and definition) and see if that helps.

**Comment by boris-kolpackov** [comment]
Ok, thanks for testing. Do you know if there is a bug report upstream for this exact problem? If not, maybe it makes sense to submit it and see what they say/plan?

While your patch is sensible, because it affects a header, it will be quite messy to apply in our package. So I was hoping we could just upgrade to latest upstream and sidestep the whole mess.

Another option to try would be to fix the call site in `fmtable.cpp:59`. It is currently:

```
return *((const Measure*) a) == *((const Measure*) b);
```

We could try explicitly calling the correct `operator==`:

```diff
diff --git a/icu4c/source/i18n/fmtable.cpp b/icu4c/source/i18n/fmtable.cpp
index dbfd3c26..00fa750a 100644
--- a/icu4c/source/i18n/fmtable.cpp
+++ b/icu4c/source/i18n/fmtable.cpp
@@ -56,7 +56,8 @@ using number::impl::DecimalQuantity;
 // Return TRUE if *a == *b.
 static inline UBool objectEquals(const UObject* a, const UObject* b) {
     // LATER: return *a == *b;
-    return *((const Measure*) a) == *((const Measure*) b);
+    //return *((const Measure*) a) == *((const Measure*) b);
+    return ((const Measure*) a)-> operator== (*((const Measure*) b));
 }
 
 // Return a clone of *a.
```

Do you think you can try that (without your patch) and see if it helps?

**Comment by boris-kolpackov** [comment]
Ok, I've published a revision with the patch to the call site. Please let me know if there are any issues. Let's also keep this bug open until a proper fix is released by upstream.

> The issue with this is that anything that relies on measures, for example, will eventually encounter problems with the operator. 

While true, this is a stop-get measure until upstream releases a proper fix. And, as I said, it saves us from wading into a big header patching mess in our package.

> Last I've check there was effectively a open issue for it but they side-stepped with Wno-ambiguous-reversed-operator on clang for now so MSVC afaik is not there yet [...]

None of the bug reports you've linked talk about a compile error in MSVC, so I think ICU folks are unaware of this (likely because this is a preview version of MSVC). I would suggest that you report this as a separate issue, if you can.

**Comment by boris-kolpackov** [comment]
I believe this is fixed and can be closed now.
